In [60]:
import numpy as np

In [61]:
arr = np.array([1,2,3,4,5])

arr.max()
arr.mean()

arr[arr > 3]

array([4, 5])

In [62]:
students = np.array([
    ["Mbappe", 9, 4],
    ["Messi", 10, 1.2],
    ["Cristiano", 7, 4],
])

gpa = students[: , 2]
gpa

array(['4', '1.2', '4'], dtype='<U32')

In [63]:
import pandas as pd

In [64]:
marks = pd.Series([70,80,80,90])

print(marks)

0    70
1    80
2    80
3    90
dtype: int64

In [65]:
students = {
    "Name": ["Mbappe", "Messi", "Ronaldo"],
    "roll": [9,10,7],
    "gpa": [4,1.2,4]
}

df = pd.DataFrame(students)

print(df)

      Name  roll  gpa
0   Mbappe     9  4.0
1    Messi    10  1.2
2  Ronaldo     7  4.0

In [66]:
df[["Name", "gpa"]]

      Name  gpa
0   Mbappe  4.0
1    Messi  1.2
2  Ronaldo  4.0

In [67]:
df["Passed"] = True

df["new_gpa"] = df["gpa"] + 0.5
print(df)

      Name  roll  gpa  Passed  new_gpa
0   Mbappe     9  4.0    True      4.5
1    Messi    10  1.2    True      1.7
2  Ronaldo     7  4.0    True      4.5

In [68]:
df.tail()

      Name  roll  gpa  Passed  new_gpa
0   Mbappe     9  4.0    True      4.5
1    Messi    10  1.2    True      1.7
2  Ronaldo     7  4.0    True      4.5

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     3 non-null      str
 1   roll     3 non-null      int64
 2   gpa      3 non-null      float64
 3   Passed   3 non-null      bool
 4   new_gpa  3 non-null      float64
dtypes: bool(1), float64(2), int64(1), str(1)
memory usage: 231.0 bytes

In [70]:
df.describe()

            roll       gpa   new_gpa
count   3.000000  3.000000  3.000000
mean    8.666667  3.066667  3.566667
std     1.527525  1.616581  1.616581
min     7.000000  1.200000  1.700000
25%     8.000000  2.600000  3.100000
50%     9.000000  4.000000  4.500000
75%     9.500000  4.000000  4.500000
max    10.000000  4.000000  4.500000

In [71]:
print(df.loc[0])
print(df.iloc[0])

Name       Mbappe
roll            9
gpa           4.0
Passed       True
new_gpa       4.5
Name: 0, dtype: object
Name       Mbappe
roll            9
gpa           4.0
Passed       True
new_gpa       4.5
Name: 0, dtype: object

In [72]:
df

      Name  roll  gpa  Passed  new_gpa
0   Mbappe     9  4.0    True      4.5
1    Messi    10  1.2    True      1.7
2  Ronaldo     7  4.0    True      4.5

In [73]:
df[df["gpa"] > 3.5]

      Name  roll  gpa  Passed  new_gpa
0   Mbappe     9  4.0    True      4.5
2  Ronaldo     7  4.0    True      4.5

In [74]:
df[df["Name"] != "Messi"]

      Name  roll  gpa  Passed  new_gpa
0   Mbappe     9  4.0    True      4.5
2  Ronaldo     7  4.0    True      4.5

In [75]:
df[
    (df["gpa"] > 1)
    &
    (df["gpa"] < 3)
]

    Name  roll  gpa  Passed  new_gpa
1  Messi    10  1.2    True      1.7

In [76]:
df["gpa"].mean()

type(df["gpa"])

pandas.Series

In [77]:
df.sort_values("gpa", ascending=False)

      Name  roll  gpa  Passed  new_gpa
0   Mbappe     9  4.0    True      4.5
2  Ronaldo     7  4.0    True      4.5
1    Messi    10  1.2    True      1.7

In [78]:
df.loc[2, ["Name", "gpa"]]

Name    Ronaldo
gpa         4.0
Name: 2, dtype: object

In [79]:
df.iloc[0, [0,2]]

Name    Mbappe
gpa        4.0
Name: 0, dtype: object

In [80]:
df

      Name  roll  gpa  Passed  new_gpa
0   Mbappe     9  4.0    True      4.5
1    Messi    10  1.2    True      1.7
2  Ronaldo     7  4.0    True      4.5

In [81]:
low_gpa_students = df[df['gpa'] < 3].index

df.drop(low_gpa_students, inplace=True)

print(df)

      Name  roll  gpa  Passed  new_gpa
0   Mbappe     9  4.0    True      4.5
2  Ronaldo     7  4.0    True      4.5

In [82]:
students = {
    "Name": ["Ram", "Sita", "Ram", "Gita", "Ram"],
    "Department": ["CS", "CS", "IT", "IT", "HR"],
    "Marks": [80, 92, 75, 88, 60]
}

df = pd.DataFrame(students)
print(df)
print(df[df["Marks"] > 80])

   Name Department  Marks
0   Ram         CS     80
1  Sita         CS     92
2   Ram         IT     75
3  Gita         IT     88
4   Ram         HR     60
   Name Department  Marks
1  Sita         CS     92
3  Gita         IT     88

In [83]:
df.groupby("Department")["Marks"].max()

Department
CS    92
HR    60
IT    88
Name: Marks, dtype: int64

In [84]:
print(df.groupby("Department")["Marks"].agg(["mean", "sum", "count"]))

            mean  sum  count
Department
CS          86.0  172      2
HR          60.0   60      1
IT          81.5  163      2

In [85]:
print(df["Marks"].agg(["mean", "max"]))

mean    79.0
max     92.0
Name: Marks, dtype: float64

In [86]:
print(
    df.groupby(["Department", "Name"])["Marks"].mean()
)

Department  Name
CS          Ram     80.0
            Sita    92.0
HR          Ram     60.0
IT          Gita    88.0
            Ram     75.0
Name: Marks, dtype: float64

In [96]:
students1 = {
    "Name": ["Ram", "Sita", "Ram", "Gita", "Ram"],
    "Department": ["CS", "CS", "IT", "IT", "HR"],
    "Marks": [80, None, 75, 88, 60]
}

df_new = pd.DataFrame(students1)
print(df_new)
df_new.isnull().sum()

   Name Department  Marks
0   Ram         CS   80.0
1  Sita         CS    NaN
2   Ram         IT   75.0
3  Gita         IT   88.0
4   Ram         HR   60.0

Name          0
Department    0
Marks         1
dtype: int64

In [98]:
df_new["Marks"] = df_new["Marks"].fillna(df_new["Marks"].mean())

In [99]:
df_new

   Name Department  Marks
0   Ram         CS  80.00
1  Sita         CS  75.75
2   Ram         IT  75.00
3  Gita         IT  88.00
4   Ram         HR  60.00